spring:
  application:
    name: meal-master-server
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-noisy-cell-a2l819sd.eu-central-1.aws.neon.tech/meal-master-db?sslmode=require}
    username: ${DATABASE_USERNAME:meal-master-db_owner}
    password: ${DATABASE_PASSWORD:2fg7prwFRlQO}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:D83fN3F4hBz8PLiT6xZ4QjRm2T9yNcBpM3Wl7jXp0Rc=}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
